namespace PF.Infrastructure.Hardware.Vision.Hikvision
{
    /// <summary>
    /// GenICam 节点中文释义表。
    ///
    /// <para><b>为什么需要它</b>：设备 XML 自带的 ToolTip 是英文且往往极简，
    /// 面对上千个节点，现场判断"这个到底是干什么的、能不能动"成本很高。</para>
    ///
    /// <para><b>数据来源</b>：主表由海康官方文档
    /// <c>工业相机Windows SDK开发指南（.NET）</c> 的「相机参数节点表」整理而来
    /// （厂商权威描述，含单位）；官方表未收录的采集卡节点、线扫/新固件节点，
    /// 以及少量操作性补充说明，由框架自行维护。</para>
    ///
    /// <para><b>操作性补充</b>是这里真正的增量：官方描述只说节点"是什么"，
    /// 而现场卡住的往往是"前提是什么"——比如 TriggerSelector 要先选、
    /// ExposureAuto 开着时 ExposureTime 只读、取流期间大量参数会被 TLParamsLocked 锁死。
    /// 这类内容附加在官方描述之后。</para>
    ///
    /// <para>刻意不收录含义不确定的节点：调试面板上一句似是而非的中文，
    /// 比一句英文原文更容易把人带偏。缺条目时补到本文件即可，不影响其他逻辑。</para>
    ///
    /// <para>匹配为**精确名**优先，其次去掉尾部数字后再试一次
    /// （EncoderSourceA / Line0 / Timer0Duration 这类带序号的节点共用同一条释义）。</para>
    /// </summary>
    internal static class GenICamNodeGlossary
    {
        /// <summary>取节点的中文释义；无对应条目时返回 null（调用方应回退设备自带描述）。</summary>
        public static string? Describe(string nodeName)
        {
            string? text = Lookup(_official, nodeName) ?? Lookup(_extra, nodeName);
            if (text == null) return null;

            string? note = Lookup(_notes, nodeName);
            return note == null ? text : $"{text}。{note}";
        }

        /// <summary>
        /// 取节点所属的官方功能分类（如 Acquisition Control）。
        /// 供设备 XML 未给出分类时回退使用；无对应条目时返回 null。
        /// </summary>
        public static string? DescribeCategory(string nodeName) => Lookup(_category, nodeName);

        /// <summary>精确名优先；再去掉结尾序号试一次。</summary>
        private static string? Lookup(Dictionary<string, string> map, string nodeName)
        {
            if (string.IsNullOrWhiteSpace(nodeName)) return null;
            if (map.TryGetValue(nodeName, out var text)) return text;

            string trimmed = nodeName.TrimEnd('0', '1', '2', '3', '4', '5', '6', '7', '8', '9');
            if (trimmed.Length > 0 && trimmed.Length != nodeName.Length
                && map.TryGetValue(trimmed, out text))
                return text;

            return null;
        }

        /// <summary>海康官方「相机参数节点表」整理所得（165 条）。</summary>
        private static readonly Dictionary<string, string> _official = new(StringComparer.Ordinal)
        {
            ["ADCGainEnable"] = "ADC 增益使能",
            ["AcquisitionBurstFrameCount"] = "一次触发采集的帧数",
            ["AcquisitionLineRate"] = "行频设置",
            ["AcquisitionLineRateEnable"] = "行频控制使能",
            ["AcquisitionMode"] = "采集模式，单帧、多帧、连续",
            ["AcquisitionStart"] = "开始取流",
            ["AcquisitionStop"] = "结束取流",
            ["ActivateShading"] = "主动校正",
            ["AutoExposureTimeLowerLimit"] = "自动曝光时间下限（单位：us）",
            ["AutoExposureTimeUpperLimit"] = "自动曝光时间上限（单位：us）",
            ["AutoFunctionAOIHeight"] = "自动 AOI 高",
            ["AutoFunctionAOIOffsetX"] = "自动 AOI 水平方向偏移",
            ["AutoFunctionAOISelector"] = "自动 AOI 选择",
            ["AutoFunctionAOIUsageIntensity"] = "根据 AOI 区域自动曝光",
            ["AutoFunctionAOIUsageWhiteBalance"] = "根据 AOI 区域自动白平衡",
            ["AutoFunctionAOIWidth"] = "自动 AOI 宽",
            ["AutoGainLowerLimit"] = "自动增益值下限（单位：dB）",
            ["AutoGainUpperLimit"] = "自动增益值上限（单位：dB）",
            ["BalanceRatio"] = "白平衡值",
            ["BalanceRatioSelector"] = "白平衡比例选择",
            ["BalanceWhiteAuto"] = "自动白平衡",
            ["BlackLevel"] = "黑电平调节",
            ["BlackLevelEnable"] = "黑电平调节使能",
            ["BoardDeviceType"] = "设备类型",
            ["Brightness"] = "亮度",
            ["DeviceCharacterSet"] = "设备寄存器中使用的字符集",
            ["DeviceConnectionSelector"] = "设备连接选择",
            ["DeviceConnectionSpeed"] = "设备连接速度（单位：Mbps）",
            ["DeviceEventChannelCount"] = "设备支持的",
            ["DeviceFirmwareVersion"] = "固件版本",
            ["DeviceID"] = "设备 ID",
            ["DeviceLinkConnectionCount"] = "设备连接数量",
            ["DeviceLinkHeartbeatMode"] = "是否需要心跳",
            ["DeviceLinkSelector"] = "设备连接选择",
            ["DeviceLinkSpeed"] = "传输链路速度",
            ["DeviceManufacturerInfo"] = "设备的制造商信息",
            ["DeviceMaxThroughput"] = "设备最大吞吐量（带宽）",
            ["DeviceModelName"] = "设备型号",
            ["DeviceReset"] = "重启设备",
            ["DeviceScanType"] = "设备 sensor 的扫描方式，表明是线阵相机还是面阵相机",
            ["DeviceSerialNumber"] = "设备序列号",
            ["DeviceStreamChannelCount"] = "流通道数量",
            ["DeviceStreamChannelEndianness"] = "图像数据的字节序",
            ["DeviceStreamChannelLink"] = "流通道连接数量",
            ["DeviceStreamChannelPacketSize"] = "接收端流数据的包大小",
            ["DeviceStreamChannelSelector"] = "流通道选择",
            ["DeviceStreamChannelType"] = "流通道类型",
            ["DeviceType"] = "设备类型",
            ["DeviceUptime"] = "设备运行时间",
            ["DeviceUserID"] = "用户自定义的名称",
            ["DeviceVendorName"] = "设备的制造商名称",
            ["DeviceVersion"] = "设备版本",
            ["DigitalShift"] = "数字偏移调节",
            ["DigitalShiftEnable"] = "数字偏移使能",
            ["EncoderCounter"] = "编码器计数器值调节",
            ["EncoderCounterMax"] = "编码器计数器最大值",
            ["EncoderCounterMode"] = "编码器计数模式",
            ["EncoderCounterReset"] = "编码器计数器复位",
            ["EncoderMaxReverseCounter"] = "编码器最大反转计数器值",
            ["EncoderReverseCounterReset"] = "编码器反转计数器复位",
            ["EncoderSelector"] = "编码器选择",
            ["EncoderSourceA"] = "编码器 A 源选择",
            ["EncoderSourceB"] = "编码器 B 源选择",
            ["EncoderTriggerMode"] = "编码器触发模式",
            ["ExposureAuto"] = "自动曝光",
            ["ExposureMode"] = "曝光模式选择",
            ["ExposureTime"] = "曝光时间（单位：us）",
            ["FrameSpecInfo"] = "是否使能该水印信息",
            ["FrameSpecInfoSelector"] = "水印信息选择",
            ["FrameTimeoutEnable"] = "帧超时使能",
            ["FrameTimeoutTime"] = "帧超时时间（单位：ms）",
            ["Gain"] = "增益值（单位：dB）",
            ["GainAuto"] = "自动增益",
            ["Gamma"] = "伽马调节",
            ["GammaEnable"] = "Gamma 使能",
            ["GammaSelector"] = "Gamma 选择",
            ["GevCCP"] = "App 端的控制权限",
            ["GevCurrentDefaultGateway"] = "默认网关",
            ["GevCurrentIPAddress"] = "IP 地址",
            ["GevCurrentIPConfigurationDHCP"] = "IP 是否为 DHCP",
            ["GevCurrentIPConfigurationLLA"] = "IP 是否为 LLA",
            ["GevCurrentIPConfigurationPersistentIP"] = "IP 是否为静态 IP",
            ["GevCurrentSubnetMask"] = "子网掩码",
            ["GevDeviceModeCharacterSet"] = "字符集",
            ["GevDeviceModeIsBigEndian"] = "大端",
            ["GevFirstURL"] = "XML 第一选择路径",
            ["GevGVCPHeartbeatDisable"] = "关闭心跳",
            ["GevHeartbeatTimeout"] = "心跳超时时间",
            ["GevInterfaceSelector"] = "GEV 接口选择",
            ["GevLinkSpeed"] = "网络速率",
            ["GevMACAddress"] = "MAC 地址",
            ["GevMessageChannelCount"] = "消息通道数",
            ["GevNumberOfInterfaces"] = "GEV 接口数",
            ["GevPersistentDefaultGateway"] = "静态默认网关",
            ["GevPersistentIPAddress"] = "静态 IP 地址",
            ["GevPersistentSubnetMask"] = "静态子网掩码",
            ["GevSCDA"] = "流数据的目的地址",
            ["GevSCPD"] = "发包延时",
            ["GevSCPDirection"] = "表明流通道方向",
            ["GevSCPHostPort"] = "主机端口",
            ["GevSCPInterfaceIndex"] = "GEV 接口索引",
            ["GevSCPSBigEndian"] = "流数据大小端",
            ["GevSCPSDoNotFragment"] = "GEV SCP不分段",
            ["GevSCPSFireTestPacket"] = "Fire Test Packet 使能",
            ["GevSCPSPacketSize"] = "网络包大小",
            ["GevSCSP"] = "流数据的源端口",
            ["GevSecondURL"] = "XML 第二选择路径",
            ["GevStreamChannelCount"] = "流通道",
            ["GevStreamChannelSelector"] = "流通道选择",
            ["GevTimestampControlLatch"] = "获取时间戳",
            ["GevTimestampControlLatchReset"] = "复位时间戳同时获取时间戳",
            ["GevTimestampControlReset"] = "复位时间戳",
            ["GevTimestampTickFrequency"] = "时间戳频率（单位：hz）",
            ["GevTimestampValue"] = "时间戳值",
            ["GevVersionMajor"] = "GEV 主版本号",
            ["GevVersionMinor"] = "GEV 子版本号",
            ["Height"] = "ROI 的高",
            ["HeightMax"] = "图像最大高度， binning 之后的数据",
            ["Hue"] = "色度值调节",
            ["HueEnable"] = "色度使能",
            ["ImageCompressionMode"] = "图像压缩模式",
            ["ImageCompressionQuality"] = "图像压缩质量",
            ["InputSource"] = "分频器输入源",
            ["LUTEnable"] = "使能",
            ["LUTIndex"] = "索引号",
            ["LUTSelector"] = "亮度、 R/G/B",
            ["LUTValue"] = "值",
            ["LineDebouncerTime"] = "I/O 去抖时间",
            ["LineMode"] = "I/O 模式",
            ["LineSelector"] = "I/O 选择",
            ["LineStatus"] = "I/O 状态",
            ["LineStatusAll"] = "所有 I/O 状态",
            ["Multiplier"] = "倍频器调节",
            ["NUCEnable"] = "NUC 使能开关",
            ["OffsetX"] = "ROI 的水平方向偏移量",
            ["OffsetY"] = "ROI 的竖直方向偏移量",
            ["PRNUCEnable"] = "PRNUC 状态开关",
            ["PayloadSize"] = "一帧数据的大小",
            ["PixelFormat"] = "图像像素格式，不同型号的相机，支持的像素格式有差异，以实际的为准",
            ["PixelSize"] = "一个像素包含的比特数",
            ["PostDivider"] = "后置分频器调节",
            ["PreDivider"] = "前置分频器调节",
            ["RegionDestination"] = "该 ROI 对应的码流",
            ["RegionSelector"] = "ROI 选择器",
            ["ResultingFrameRate"] = "相机的实际采集帧率（单位：fps）",
            ["ResultingLineRate"] = "实际行频（单位：hz）",
            ["ReverseScanDirection"] = "转换扫描方向",
            ["Saturation"] = "饱和度值调节",
            ["SaturationEnable"] = "饱和度使能",
            ["ShadingSelector"] = "明暗场校正选择",
            ["SignalAlignment"] = "分频器信号方向",
            ["TestPattern"] = "测试图像选择",
            ["TestPatternGeneratorSelector"] = "测试图像生成器选择",
            ["TriggerActivation"] = "触发上升沿、下降沿、高电平、低电平等",
            ["TriggerDelay"] = "触发延时（单位：us）",
            ["TriggerMode"] = "触发模式",
            ["TriggerSelector"] = "触发事件选择",
            ["TriggerSource"] = "触发源",
            ["UserSetCurrent"] = "当前用户参数",
            ["UserSetDefault"] = "默认状态",
            ["UserSetLoad"] = "加载",
            ["UserSetSave"] = "保存",
            ["UserSetSelector"] = "设置载入的参数",
            ["Width"] = "ROI 的宽",
            ["WidthMax"] = "图像最大宽度， binning 之后的数据",
        };

        /// <summary>官方表给出的功能分类，用作属性树分类列的回退。</summary>
        private static readonly Dictionary<string, string> _category = new(StringComparer.Ordinal)
        {
            ["ADCGainEnable"] = "Analog Control",
            ["AcquisitionBurstFrameCount"] = "Acquisition Control",
            ["AcquisitionLineRate"] = "Acquisition Control",
            ["AcquisitionLineRateEnable"] = "Acquisition Control",
            ["AcquisitionMode"] = "Acquisition Control",
            ["AcquisitionStart"] = "Acquisition Control",
            ["AcquisitionStop"] = "Acquisition Control",
            ["ActivateShading"] = "Shading Correction",
            ["AutoExposureTimeLowerLimit"] = "Acquisition Control",
            ["AutoExposureTimeUpperLimit"] = "Acquisition Control",
            ["AutoFunctionAOIHeight"] = "Analog Control",
            ["AutoFunctionAOIOffsetX"] = "Analog Control",
            ["AutoFunctionAOISelector"] = "Analog Control",
            ["AutoFunctionAOIUsageIntensity"] = "Analog Control",
            ["AutoFunctionAOIUsageWhiteBalance"] = "Analog Control",
            ["AutoFunctionAOIWidth"] = "Analog Control",
            ["AutoGainLowerLimit"] = "Analog Control",
            ["AutoGainUpperLimit"] = "Analog Control",
            ["BalanceRatio"] = "Analog Control",
            ["BalanceRatioSelector"] = "Analog Control",
            ["BalanceWhiteAuto"] = "Analog Control",
            ["BlackLevel"] = "Analog Control",
            ["BlackLevelEnable"] = "Analog Control",
            ["BoardDeviceType"] = "Device Control",
            ["Brightness"] = "Analog Control",
            ["DeviceCharacterSet"] = "Device Control",
            ["DeviceConnectionSelector"] = "Device Control",
            ["DeviceConnectionSpeed"] = "Device Control",
            ["DeviceEventChannelCount"] = "Device Control",
            ["DeviceFirmwareVersion"] = "Device Control",
            ["DeviceID"] = "Device Control",
            ["DeviceLinkConnectionCount"] = "Device Control",
            ["DeviceLinkHeartbeatMode"] = "Device Control",
            ["DeviceLinkSelector"] = "Device Control",
            ["DeviceLinkSpeed"] = "Device Control",
            ["DeviceManufacturerInfo"] = "Device Control",
            ["DeviceMaxThroughput"] = "Device Control",
            ["DeviceModelName"] = "Device Control",
            ["DeviceReset"] = "Device Control",
            ["DeviceScanType"] = "Device Control",
            ["DeviceSerialNumber"] = "Device Control",
            ["DeviceStreamChannelCount"] = "Device Control",
            ["DeviceStreamChannelEndianness"] = "Device Control",
            ["DeviceStreamChannelLink"] = "Device Control",
            ["DeviceStreamChannelPacketSize"] = "Device Control",
            ["DeviceStreamChannelSelector"] = "Device Control",
            ["DeviceStreamChannelType"] = "Device Control",
            ["DeviceType"] = "Device Control",
            ["DeviceUptime"] = "Device Control",
            ["DeviceUserID"] = "Device Control",
            ["DeviceVendorName"] = "Device Control",
            ["DeviceVersion"] = "Device Control",
            ["DigitalShift"] = "Analog Control",
            ["DigitalShiftEnable"] = "Analog Control",
            ["EncoderCounter"] = "Encoder Control",
            ["EncoderCounterMax"] = "Encoder Control",
            ["EncoderCounterMode"] = "Encoder Control",
            ["EncoderCounterReset"] = "Encoder Control",
            ["EncoderMaxReverseCounter"] = "Encoder Control",
            ["EncoderReverseCounterReset"] = "Encoder Control",
            ["EncoderSelector"] = "Encoder Control",
            ["EncoderSourceA"] = "Encoder Control",
            ["EncoderSourceB"] = "Encoder Control",
            ["EncoderTriggerMode"] = "Encoder Control",
            ["ExposureAuto"] = "Acquisition Control",
            ["ExposureMode"] = "Acquisition Control",
            ["ExposureTime"] = "Acquisition Control",
            ["FrameSpecInfo"] = "Image Format Control",
            ["FrameSpecInfoSelector"] = "Image Format Control",
            ["FrameTimeoutEnable"] = "Acquisition Control",
            ["FrameTimeoutTime"] = "Acquisition Control",
            ["Gain"] = "Analog Control",
            ["GainAuto"] = "Analog Control",
            ["Gamma"] = "Analog Control",
            ["GammaEnable"] = "Analog Control",
            ["GammaSelector"] = "Analog Control",
            ["GevCCP"] = "Transport Layer Control",
            ["GevCurrentDefaultGateway"] = "Transport Layer Control",
            ["GevCurrentIPAddress"] = "Transport Layer Control",
            ["GevCurrentIPConfigurationDHCP"] = "Transport Layer Control",
            ["GevCurrentIPConfigurationLLA"] = "Transport Layer Control",
            ["GevCurrentIPConfigurationPersistentIP"] = "Transport Layer Control",
            ["GevCurrentSubnetMask"] = "Transport Layer Control",
            ["GevDeviceModeCharacterSet"] = "Transport Layer Control",
            ["GevDeviceModeIsBigEndian"] = "Transport Layer Control",
            ["GevFirstURL"] = "Transport Layer Control",
            ["GevGVCPHeartbeatDisable"] = "Transport Layer Control",
            ["GevHeartbeatTimeout"] = "Transport Layer Control",
            ["GevInterfaceSelector"] = "Transport Layer Control",
            ["GevLinkSpeed"] = "Transport Layer Control",
            ["GevMACAddress"] = "Transport Layer Control",
            ["GevMessageChannelCount"] = "Transport Layer Control",
            ["GevNumberOfInterfaces"] = "Transport Layer Control",
            ["GevPersistentDefaultGateway"] = "Transport Layer Control",
            ["GevPersistentIPAddress"] = "Transport Layer Control",
            ["GevPersistentSubnetMask"] = "Transport Layer Control",
            ["GevSCDA"] = "Transport Layer Control",
            ["GevSCPD"] = "Transport Layer Control",
            ["GevSCPDirection"] = "Transport Layer Control",
            ["GevSCPHostPort"] = "Transport Layer Control",
            ["GevSCPInterfaceIndex"] = "Transport Layer Control",
            ["GevSCPSBigEndian"] = "Transport Layer Control",
            ["GevSCPSDoNotFragment"] = "Transport Layer Control",
            ["GevSCPSFireTestPacket"] = "Transport Layer Control",
            ["GevSCPSPacketSize"] = "Transport Layer Control",
            ["GevSCSP"] = "Transport Layer Control",
            ["GevSecondURL"] = "Transport Layer Control",
            ["GevStreamChannelCount"] = "Transport Layer Control",
            ["GevStreamChannelSelector"] = "Transport Layer Control",
            ["GevTimestampControlLatch"] = "Transport Layer Control",
            ["GevTimestampControlLatchReset"] = "Transport Layer Control",
            ["GevTimestampControlReset"] = "Transport Layer Control",
            ["GevTimestampTickFrequency"] = "Transport Layer Control",
            ["GevTimestampValue"] = "Transport Layer Control",
            ["GevVersionMajor"] = "Transport Layer Control",
            ["GevVersionMinor"] = "Transport Layer Control",
            ["Height"] = "Image Format Control",
            ["HeightMax"] = "Image Format Control",
            ["Hue"] = "Analog Control",
            ["HueEnable"] = "Analog Control",
            ["ImageCompressionMode"] = "Image Format Control",
            ["ImageCompressionQuality"] = "Image Format Control",
            ["InputSource"] = "Frequency Converter Control",
            ["LUTEnable"] = "LUT Control",
            ["LUTIndex"] = "LUT Control",
            ["LUTSelector"] = "LUT Control",
            ["LUTValue"] = "LUT Control",
            ["LineDebouncerTime"] = "Digital IO Control",
            ["LineMode"] = "Digital IO Control",
            ["LineSelector"] = "Digital IO Control",
            ["LineStatus"] = "Digital IO Control",
            ["LineStatusAll"] = "Digital IO Control",
            ["Multiplier"] = "Frequency Converter Control",
            ["NUCEnable"] = "Shading Correction",
            ["OffsetX"] = "Image Format Control",
            ["OffsetY"] = "Image Format Control",
            ["PRNUCEnable"] = "Shading Correction",
            ["PayloadSize"] = "Transport Layer Control",
            ["PixelFormat"] = "Image Format Control",
            ["PixelSize"] = "Image Format Control",
            ["PostDivider"] = "Frequency Converter Control",
            ["PreDivider"] = "Frequency Converter Control",
            ["RegionDestination"] = "Image Format Control",
            ["RegionSelector"] = "Image Format Control",
            ["ResultingFrameRate"] = "Acquisition Control",
            ["ResultingLineRate"] = "Acquisition Control",
            ["ReverseScanDirection"] = "Image Format Control",
            ["Saturation"] = "Analog Control",
            ["SaturationEnable"] = "Analog Control",
            ["ShadingSelector"] = "Shading Correction",
            ["SignalAlignment"] = "Frequency Converter Control",
            ["TestPattern"] = "Image Format Control",
            ["TestPatternGeneratorSelector"] = "Image Format Control",
            ["TriggerActivation"] = "Acquisition Control",
            ["TriggerDelay"] = "Acquisition Control",
            ["TriggerMode"] = "Acquisition Control",
            ["TriggerSelector"] = "Acquisition Control",
            ["TriggerSource"] = "Acquisition Control",
            ["UserSetCurrent"] = "User Set Control",
            ["UserSetDefault"] = "User Set Control",
            ["UserSetLoad"] = "User Set Control",
            ["UserSetSave"] = "User Set Control",
            ["UserSetSelector"] = "User Set Control",
            ["Width"] = "Image Format Control",
            ["WidthMax"] = "Image Format Control",
        };

        /// <summary>官方表未收录的节点：采集卡节点树、线扫/新固件节点等。</summary>
        private static readonly Dictionary<string, string> _extra = new(StringComparer.Ordinal)
        {
            ["AcquisitionFrameRate"] = "采集帧率",
            ["AcquisitionFrameRateEnable"] = "启用帧率控制。不启用时按曝光与传输能力自由出图",
            ["BayerCFAEnable"] = "卡侧 Bayer 转换使能",
            ["BinningHorizontal"] = "水平合并像素数：提高灵敏度、降低分辨率",
            ["BinningVertical"] = "垂直合并像素数",
            ["CameraType"] = "相机类型/位宽匹配。CameraLink 必须与相机侧一致，不一致的典型表现是出不了图或图像横向错位",
            ["ChunkEnable"] = "启用所选附加信息项",
            ["ChunkModeActive"] = "帧附加信息（Chunk）开关",
            ["ChunkSelector"] = "附加信息项选择",
            ["CounterEventSource"] = "计数事件源",
            ["CounterReset"] = "计数器清零",
            ["CounterSelector"] = "计数器选择",
            ["CounterValue"] = "计数器当前值",
            ["CurrentStreamDevice"] = "当前流绑定的相机（只读）。未绑定相机时，ImageHeight 等流参数不可写",
            ["DSNUEnable"] = "暗场非均匀性校正开关",
            ["DecimationHorizontal"] = "水平抽点：隔点取样，降低分辨率与数据量",
            ["DecimationVertical"] = "垂直抽点",
            ["DeviceTemperature"] = "设备当前温度",
            ["DeviceTemperatureSelector"] = "温度测点选择，选定后由 DeviceTemperature 读数",
            ["EncoderDivider"] = "编码器分频系数：每 N 个脉冲触发一行，直接决定行间距",
            ["EncoderMultiplier"] = "编码器倍频系数",
            ["EncoderOutputMode"] = "编码器输出模式",
            ["EncoderResetSource"] = "编码器计数复位信号源",
            ["EventNotification"] = "事件上报开关",
            ["EventSelector"] = "事件选择",
            ["FFCCoefficient"] = "平场校正系数",
            ["FFCEnable"] = "平场校正开关。线扫必备：补偿光照不均与像元响应差异",
            ["FFCGenerate"] = "生成平场校正数据。需在均匀白场下执行",
            ["FFCGenerateStatus"] = "平场校正数据生成状态",
            ["FFCUserCoefficientSelector"] = "平场校正系数组选择",
            ["FrameTriggerControl"] = "帧触发控制组（新固件才有）",
            ["FrameTriggerMode"] = "帧触发开关：开启后由外部信号决定一帧从哪里开始",
            ["FrameTriggerSource"] = "帧触发源",
            ["ImageCompressionMode"] = "无损压缩模式。开启后取到的是压缩流，需先解码才是可按宽高解析的裸像素",
            ["ImageHeight"] = "帧长：一帧累计多少行。经采集卡取流时，线扫的帧长写在这里而不是相机的 Height",
            ["InterfaceID"] = "采集卡标识",
            ["IspGamma"] = "卡侧伽马值",
            ["IspGammaEnable"] = "卡侧伽马使能",
            ["LineFormat"] = "电气类型：OptoCoupled 光耦 / TTL / LVDS",
            ["LineInverter"] = "电平反相",
            ["LineMode"] = "IO 线模式：Input 输入 / Output 输出 / Strobe 闪光",
            ["LineSource"] = "输出线的信号来源：ExposureActive 曝光中 / StrobeSignal 闪光 / UserOutput 用户自定义",
            ["LineSpacing"] = "行间距",
            ["LineTriggerControl"] = "行触发控制组。存在与否可用来判断固件走新节点树还是老节点树",
            ["LineTriggerMode"] = "行触发开关：开启后每行由外部信号驱动，关闭则按内部行频",
            ["LineTriggerSource"] = "行触发源。编码器模式下取 EncoderModuleOut",
            ["MinFrameDelay"] = "最小帧间隔",
            ["NoiseReduction"] = "降噪强度",
            ["PRNUEnable"] = "像元响应非均匀性校正开关",
            ["PartialImageOutputMode"] = "残帧输出策略（XoF 卡）：不足一帧的数据是否输出",
            ["PreampGain"] = "模拟增益档位（枚举而非数值）。在 AD 转换前放大，噪声表现优于数字增益",
            ["QuickSoftwareTrigger"] = "快速软触发，延迟低于普通软触发，仅部分卡固件支持",
            ["ReverseX"] = "图像水平镜像",
            ["ReverseY"] = "图像垂直镜像",
            ["ScanMode"] = "扫描模式：LineScan 线阵 / FrameScan 面阵",
            ["Sharpness"] = "锐度",
            ["SharpnessEnable"] = "锐化使能",
            ["StreamEnableStatus"] = "流使能状态",
            ["StreamPartialImageControl"] = "残帧输出策略（CameraLink 卡）",
            ["StreamSelector"] = "流通道选择。一卡多路时先选它，之后的流参数才是针对这一路的",
            ["StreamSoftwareTrigger"] = "发送一次卡侧帧软触发。需先开启 StreamTriggerEnable，否则报节点访问条件有误",
            ["StreamTriggerActivation"] = "卡侧帧触发有效边沿",
            ["StreamTriggerEnable"] = "卡侧帧触发开关。关闭即连续模式，攒满帧长自动出图。XoF 卡无此节点",
            ["StreamTriggerSource"] = "卡侧帧触发源：SoftwareSignal0 软触发 / QuickSoftwareTrigger0 快速软触发（需固件支持）/ 硬件信号",
            ["StrobeEnable"] = "闪光输出使能",
            ["StrobeLineDelay"] = "闪光延时",
            ["StrobeLineDuration"] = "闪光持续时间",
            ["StrobeLinePreDelay"] = "闪光提前量，用于补偿光源自身的点亮延迟",
            ["StrobeLineSelector"] = "闪光输出线选择",
            ["TLParamsLocked"] = "取流期间参数锁定（只读）。取流中大量参数会因此转为只读，改参数前先停流",
            ["TimerDelay"] = "定时器延时",
            ["TimerDuration"] = "定时器时长",
            ["TimerSelector"] = "定时器选择",
            ["TriggerCacheEnable"] = "触发缓存：相机忙时到来的触发信号是否缓存下来补发",
            ["TriggerSoftware"] = "发送一次软触发。需先把 TriggerSource 设为 Software",
            ["UserOutputSelector"] = "用户输出位选择",
            ["UserOutputValue"] = "用户输出位电平",
        };

        /// <summary>操作性补充：官方描述之外，会影响现场操作的前提与副作用。</summary>
        private static readonly Dictionary<string, string> _notes = new(StringComparer.Ordinal)
        {
            ["AcquisitionLineRate"] = "受曝光时间限制：曝光越长，可达行频越低",
            ["AcquisitionLineRateEnable"] = "台架上没有编码器时开启它，相机按内部时钟自行逐行曝光，可用来先验证出图链路",
            ["BalanceRatioSelector"] = "先选它，BalanceRatio 才是针对该通道的",
            ["DeviceReset"] = "执行后连接会断开，需要重新连接",
            ["EncoderMaxReverseCounter"] = "允许的最大反向计数；超过后需重新正向运动才恢复出触发，用于抑制往复抖动重复触发",
            ["EncoderSelector"] = "先选它，之后的编码器参数才是针对这一路的",
            ["ExposureAuto"] = "开启时 ExposureTime 转为只读",
            ["GainAuto"] = "开启时 Gain 转为只读",
            ["GevSCPSPacketSize"] = "设为链路支持的最大值可显著降低丢包与 CPU 占用；超过链路 MTU 会直接收不到图",
            ["Height"] = "线扫相机直连（不经采集卡）时，它就是一帧累计多少行",
            ["LUTSelector"] = "先选它，LUTIndex / LUTValue 才是针对该查找表的",
            ["LineDebouncerTime"] = "短于此时长的脉冲被忽略，用于抑制干扰造成的误触发",
            ["LineSelector"] = "先选它，之后的 Line* 参数才是针对这一路 IO 的",
            ["PayloadSize"] = "单帧数据大小，可据此估算内存占用",
            ["PixelFormat"] = "改它会影响可用的压缩模式，改完需重读 ImageCompressionMode",
            ["RegionSelector"] = "先选它，之后的 Width / Height / Offset* 才是针对这个 ROI 的",
            ["ShadingSelector"] = "先选它，ActivateShading 才是针对该项校正的",
            ["TestPattern"] = "出图异常时用它区分：能出测试图说明传输正常，问题在传感器或光路",
            ["TriggerDelay"] = "信号到达后延迟这么久才真正触发",
            ["TriggerSelector"] = "先选它，之后的 TriggerMode / TriggerSource / TriggerActivation 才是针对这一类触发的",
            ["UserSetLoad"] = "会覆盖当前全部参数",
            ["UserSetSave"] = "Default 组不可写，只能存到 UserSet1~3",
        };
    }
}
